[phases.setup]
nixPkgs = [
    "python311",
    "nodejs",
    "python311Packages.flask",
    "python311Packages.flask-cors",
    "python311Packages.requests",
    "python311Packages.pandas",
    "python311Packages.openpyxl",
    "python311Packages.python-dotenv",
    "python311Packages.gunicorn",
    "python311Packages.pip",
    "gcc"
]

[phases.install]
cmds = [
    "echo 'Python dependencies managed by Nix.'"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/build/* backend/static/",
    "which gunicorn"
]

[start]
cmd = "cd backend && PYTHONPATH=/root/.nix-profile/lib/python3.11/site-packages python3 -m gunicorn --bind 0.0.0.0:$PORT app:app"

