[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
    "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python3 get-pip.py",
    "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "mkdir -p ../backend/static",
    "cp -r build/* ../backend/static/"
]

[start]
cmd = "cd backend && python3 -m gunicorn --bind 0.0.0.0:$PORT app:app"