[phases.setup]
nixPkgs = ["python311", "nodejs", "python3Packages.pip", "gcc"]

[phases.install]
cmds = [
    "echo 'Python dependencies managed by Nix.'"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "mkdir -p ../backend/static",
    "cp -r build/* ../backend/static/"
]

[start]
cmd = "cd backend && python3 -m gunicorn --bind 0.0.0.0:$PORT app:app"