[phases.setup]
nixPkgs = ["python311", "nodejs", "gcc"]

[phases.install]
cmds = [
    "python3 -m ensurepip --upgrade",
    "cd backend && pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "mkdir -p ../backend/static",
    "cp -r build/* ../backend/static/"
]

[start]
cmd = "cd backend && python3 -m gunicorn app:app"