[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "cd backend && pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "mkdir -p ../backend/static",
    "cp -r build/* ../backend/static/"
]

[start]
cmd = "source /opt/venv/bin/activate && cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"