[phases.setup]
nixPkgs = [
    "python311",
    "nodejs",
    "python311Packages.flask",
    "python311Packages.flask-cors",
    "python311Packages.requests",
    "python311Packages.urllib3",
    "python311Packages.charset-normalizer",
    "python311Packages.pandas",
    "python311Packages.et_xmlfile",
    "python311Packages.numpy",
    "python311Packages.pytz",
    "python311Packages.openpyxl",
    "python311Packages.python-dotenv",
    "python311Packages.gunicorn",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "python311Packages.typing-extensions",
    "python311Packages.cryptography",
    "python311Packages.python-dateutil",
    "python311Packages.six",
    "python311Packages.certifi",
    "python311Packages.idna",
    "gcc"
]

[phases.install]
cmds = [
    "echo 'Python dependencies managed by Nix.'"
]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/build/* backend/static/",
    "which gunicorn"
]

[start]
cmd = "cd backend && PYTHONPATH=$PYTHONPATH:/root/.nix-profile/lib/python3.11/site-packages gunicorn --bind 0.0.0.0:$PORT app:app"

