[
build
]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[
deploy
]
startCommand = "cd backend && gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"