[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && PYTHONPATH=$PYTHONPATH:/root/.nix-profile/lib/python3.11/site-packages gunicorn --bind 0.0.0.0:$PORT app:app"
restartPolicyType = "on_failure"