[build]
builder = "nixpacks"

[deploy]
startCommand = "source /opt/venv/bin/activate && cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"

[deploy.envs]
NIXPACKS_PYTHON_VERSION = "3.11"